name: Crowdloans

on:
  schedule:
    # Run every 30 seconds
    - cron: "*/1 * * * * *"

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Get Crowdloan Value
        id: crowdloan
        run: echo "::set-output name=value::$(yarn start)"

      - name: Check if Issue Exists
        id: issue_exists
        uses: peter-evans/create-or-update-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: <owner>/<repo>
          title: "[Crowdloan] New ${{ steps.crowdloan.outputs.value }}"
          body: "A new crowdloan value of ${{ steps.crowdloan.outputs.value }} was detected."
          labels: "crowdloan"
          assignees: "octocat"

      - name: Skip If Issue Exists
        if: steps.issue_exists.outputs.created == 'false'
        run: exit 1

      - name: Issue Created
        run: echo "New issue created"
