name: crowdloan-cronjob

on:
  schedule:
    - cron: "* */1 * * *" # Every hour

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Crowdloans
        env:
          OCTOKIT_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
        run: yarn start
